### ISSUE TITLE
How do I delete entries?

### ISSUE THREAD

**Issue by JordanDevelop** [brightcove-archive/zencoder_zensockets#1]
I tried deleting from the /db/media file but that didn't do anything. I'm used to using MongoDB.

**Comment by mmcc** [comment]
This demo uses [NeDB](https://github.com/louischatriot/nedb), which you can think of as a NoSQL version of SQLite. It's just a flat file database and the API is a subset of MongoDB.

To clarify, you just tried to edit the database file and it didn't work? Keep in mind that NeDB doesn't actually _update_ entries in the db file, it appends a new version of that entry. When the application is restarted, NeDB will go through and flatten the file so it only has one version, but if you deleted one and not any of the others, it will still show up.

I would suggest using the API, though. If you're used to using MongoDB, this should be [pretty straightforward](https://github.com/louischatriot/nedb#removing-documents). You could even just use that to create a new `/delete` route :)
